config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'customers#index'
  get 'customers/alphabetized', to: 'customers#alphabetized', as: 'alphabetized'
  get 'customers/missing_email', to: 'customers#missing_email', as: 'missing_email'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, presence: true

  belongs_to :province
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(:email_address => '')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="customer">
  <p class="full_name"><%= customer.full_name %></p>
  <%= image_tag customer.image, alt: customer.full_name %>
  <p>
    <span class="province">Province: </span>
    <%=customer.province_id.nil? ? 'None' : customer.province.name %>
  </p>
  <p class="phone_number"><%= customer.phone_number %></p>
  <p class="email_address"><%= customer.email_address %></p>
</div>

app/views/customers/alphabetized.html.erb
<%= render partial: "customer", collection: @customers %>

app/views/customers/index.html.erb
<h1>All Customers</h1>
<%= render partial: "customer", collection: @customers %>
<div id="links">
  <%= link_to 'Alphabetized', alphabetized_path %>
  <%= link_to 'Missing Email', missing_email_path %>
</div>

app/views/customers/missing_email.html.erb
<%= render partial: "customer", collection: @customers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U6Crm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>